name: Auto Deploy

on:
  push:
    branches: [main]
    paths:
      - 'server/**'
      - '.github/workflows/**'

concurrency:
  group: auto-deploy
  cancel-in-progress: true

jobs:
  deploy:
    name: Auto Deploy to Development
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: server/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION || 'us-east-1' }}

      - name: Store secrets in AWS Parameter Store
        run: |
          aws ssm put-parameter --name "/aiphoto/dev/google-gemini-api-key" --value "${{ secrets.GOOGLE_GEMINI_API_KEY }}" --type "SecureString" --overwrite || true
          aws ssm put-parameter --name "/aiphoto/dev/sentry-dsn" --value "${{ secrets.SENTRY_DSN }}" --type "SecureString" --overwrite || true

      - name: Deploy to AWS
        run: |
          npx cdk bootstrap --require-approval never || true
          npx cdk deploy --require-approval never

      - name: Test deployment
        run: |
          # Get the API endpoint from CloudFormation outputs
          API_ENDPOINT=$(aws cloudformation describe-stacks --stack-name aiphoto-prod --query 'Stacks[0].Outputs[?OutputKey==`ApiEndpoint`].OutputValue' --output text)
          echo "Testing API at: $API_ENDPOINT"
          
          # Test health endpoint
          curl -f "$API_ENDPOINT/health" || exit 1
          echo "✅ Health check passed"

      - name: Notify on success
        if: success()
        run: |
          echo "🚀 Deployment successful!"
          echo "API Endpoint: $(aws cloudformation describe-stacks --stack-name aiphoto-prod --query 'Stacks[0].Outputs[?OutputKey==`ApiEndpoint`].OutputValue' --output text)"

      - name: Notify on failure
        if: failure()
        run: |
          echo "❌ Deployment failed!"
          exit 1