name: Deploy AI Photo Server

on:
  push:
    branches: [ main, production ]
  pull_request:
    branches: [ main ]

env:
  NODE_VERSION: '22'
  AWS_REGION: 'us-east-1'

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: aiphoto_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        working-directory: ./server
        run: npm ci

      - name: Run type checking
        working-directory: ./server
        run: npm run typecheck

      - name: Run linting
        working-directory: ./server
        run: npm run lint

      - name: Run tests
        working-directory: ./server
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/aiphoto_test
          NODE_ENV: test
          GOOGLE_GEMINI_API_KEY: test-key
          COGNITO_USER_POOL_ID: test-pool
          COGNITO_REGION: us-east-1
          S3_BUCKET_NAME: test-bucket
        run: npm test

  build:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/production'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        working-directory: ./server
        run: npm ci

      - name: Build application
        working-directory: ./server
        run: npm run build

      - name: Create deployment package
        working-directory: ./server
        run: |
          # Create deployment package with all necessary files
          mkdir -p deployment-package
          
          # Copy built application
          cp -r dist deployment-package/
          cp package.json package-lock.json deployment-package/
          cp -r drizzle deployment-package/
          
          # Copy CodeDeploy files
          cp appspec.yml deployment-package/
          cp -r scripts deployment-package/
          
          # Create tar file
          cd deployment-package
          tar -czf ../deployment-package.tar.gz .
          cd ..
          
          # Also create ZIP for CodeDeploy
          cd deployment-package
          zip -r ../deployment-package.zip .

      - name: Upload deployment package
        uses: actions/upload-artifact@v4
        with:
          name: deployment-package
          path: |
            server/deployment-package.tar.gz
            server/deployment-package.zip
          retention-days: 30

  deploy-production:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/production'
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy CloudFormation Stack
        run: |
          # Deploy with minimal required secrets - add more to GitHub secrets as needed
          aws cloudformation deploy \
            --template-file server/cloudformation/infrastructure.yaml \
            --stack-name aiphoto-production \
            --parameter-overrides \
              Environment=production \
              InstanceType=t3.medium \
              KeyPairName="${{ secrets.KEY_PAIR_NAME || 'aiphoto-production' }}" \
              DatabaseUrl="${{ secrets.DATABASE_URL || 'postgresql://postgres:postgres@localhost:5432/aiphoto' }}" \
              RedisUrl="${{ secrets.REDIS_URL || 'redis://localhost:6379' }}" \
              CognitoUserPoolId="${{ secrets.COGNITO_USER_POOL_ID || 'us-east-1_64yfVC7J5' }}" \
              CognitoRegion="${{ secrets.COGNITO_REGION || 'us-east-1' }}" \
              GeminiApiKey="${{ secrets.GOOGLE_GEMINI_API_KEY }}" \
              S3BucketName="${{ secrets.S3_BUCKET_NAME || 'aiphoto-images-dev' }}" \
              CorsOrigin="${{ secrets.CORS_ORIGIN || 'http://localhost:3000,http://localhost:19006' }}" \
              GitHubRepo="${{ github.repository }}" \
            --capabilities CAPABILITY_NAMED_IAM \
            --region ${{ env.AWS_REGION }}

      - name: Download deployment package
        uses: actions/download-artifact@v4
        with:
          name: deployment-package

      - name: Upload to S3 and Deploy via CodeDeploy
        run: |
          # Upload deployment package to S3
          aws s3 cp deployment-package.zip s3://aiphoto-codedeploy-bucket/aiphoto-production/deployment-package-${{ github.sha }}.zip
          
          # Get deployment group info
          APP_NAME=$(aws cloudformation describe-stacks --stack-name aiphoto-production --query 'Stacks[0].Outputs[?OutputKey==`CodeDeployApplicationName`].OutputValue' --output text)
          DEPLOYMENT_GROUP=$(aws cloudformation describe-stacks --stack-name aiphoto-production --query 'Stacks[0].Outputs[?OutputKey==`CodeDeployDeploymentGroupName`].OutputValue' --output text)
          
          # Create deployment
          aws deploy create-deployment \
            --application-name $APP_NAME \
            --deployment-group-name $DEPLOYMENT_GROUP \
            --s3-location bucket=aiphoto-codedeploy-bucket,key=aiphoto-production/deployment-package-${{ github.sha }}.zip,bundleType=zip